### ISSUE TITLE
[Feature] Make it easy to encrypt the database and send it to third party storage

### ISSUE THREAD

**Issue by YPCrumble** [tj-actions/pg-dump#120]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like?

I'm basically looking to use this GH action as a full-featured way to create PSQL database backups and send them, encrypted, to a storage somewhere. I'd like it to be as simple and foolproof as possible, so potentially sending the encrypted database to Dropbox would be easy to manage.

I'd be happy to help with a PR if this seems like an appropriate/doable feature for the repo!

### Describe alternatives you've considered?

backupsheep.com, simplebackups.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @YPCrumble, Sorry for getting back to you so late on this I'll be happy to review a PR related to this.

**Comment by jackton1** [comment]
Due to lack of activity I’ll be closing this issue but I’m open to reviewing a PR that addresses this issue
