### ISSUE TITLE
[BUG] postgres_version: "16" is failing

### ISSUE THREAD

**Issue by apfromiit** [tj-actions/pg-dump#142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

# Logs:

Run tj-actions/pg-dump@v3
Run tj-actions/install-postgresql@v2
  
Run bash $GITHUB_ACTION_PATH/entrypoint.sh
setup-postgresql
  Verifying version
  Error: 16 is not between 10 and 15 (inclusive).
  Error: Process completed with exit code 1.

### To Reproduce

1. runs-on: ubuntu-latest
2. postgresql_version: "16"

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-22.04

### Expected behavior?

Please add support for latest version of postgres

### Relevant log output

```shell
Run tj-actions/pg-dump@v3
Run tj-actions/install-postgresql@v2
  
Run bash $GITHUB_ACTION_PATH/entrypoint.sh
setup-postgresql
  Verifying version
  Error: 16 is not between 10 and 15 (inclusive).
  Error: Process completed with exit code 1.
```

### Has all relevant logs been included?

- [X] I've included all relevant logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @apfromiit you'll need to upgrade to the latest version v3 instead of v2. Which has support for version 16

**Comment by apfromiit** [comment]
It worked now. Thanks.

**Comment by jackton1** [comment]
Your welcome
