### ISSUE TITLE
[Feature] Choose Postgres version

### ISSUE THREAD

**Issue by yovanoc** [tj-actions/pg-dump#35]
### Is your feature request related to a problem? Please describe.

I actually have a Postgres 14 db but the action trigger that a version mismatch occur

### Describe the solution you'd like?

configure the version in the yml

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
The action is version agnostic, you should be able to run any version of Postgres, however there was a bug passing options via the input you can upgrade to the latest version and verify that the issue is resolved. 

You can also add a bug report including any relevant logs.
